### ISSUE TITLE
Price field incorrect if only DLC options listed

### ISSUE THREAD

**Issue by SGColdSun** [prncc/steam-scraper#2]
In instances where a game doesn't have a price but has tons of DLC, the sum of the DLC is added as the base price for the title.

Correct approach would be to change the 
price = response.css('.game_purchase_price ::text').extract_first()
to either verify that it's parent element isn't  "dlc_purchase_action" 
or to verify that the hierarchy contains the class "game_area_purchase_game"

**Comment by prncc** [comment]
Do you have an example of a game like that? It doesn't seem to be the case for, say, http://store.steampowered.com/app/591530/Hyper_Universe/.
