### ISSUE TITLE
Recommended column is not being filled

### ISSUE THREAD

**Issue by MR1991** [prncc/steam-scraper#4]
Thank you for the scraper!
 
One note, for me it didn't properly take the recommended value, it just always gave a TRUE result.
So in the items.py file I changed the following from: 
```
    recommended = scrapy.Field(
        input_processor=simplify_recommended,
        output_processor=TakeFirst(),
    )
```
To the below and now it works (again):

```
 recommended = scrapy.Field(
        output_processor=Compose(TakeFirst(), str_to_float)
    )
```

**Comment by prncc** [comment]
Thanks, this should be fixed now.
