### ISSUE TITLE
Decoding unicode escaped characters

### ISSUE THREAD

**Issue by ArtyCooL** [prncc/steam-scraper#6]
Hi! Thank you for this useful Scrapy spider!
Beforehand I would like to say that I'm a newbie in using Python.
I have an issue with foreign reviews (Russian, Chinese, Japanese etc.). In my output file (reviews.jl) these reviews display as \u0441\u043b\u0438\u0448\u043a\u043e\u043c etc. (after decoding it looks like this "слишком")
Is there any workaround for this issue - any chance of changing the script code so that the review text will export correctly without unicode escaped characters.

Right now I'm using Notepad++ plugin called HTMLPad to Decode JS. It works but it can't decode large amount of text at once (26000 reviews for example), so I have to select 100-200 strings and decode them manually which is real pain in the ass for 26000 reviews...

**Comment by zhenzuo2** [comment]
Hello. I have the same problem when I am dealing with foreign languages. I think for different language, different decoding method should be applied. 
http://zempirians.com/ebooks/Steven%20Bird,%20Ewan%20Klein,%20Edward%20Loper-Natural%20Language%20Processing%20with%20Python-O'Reilly%20Media%20(2009).pdf

This may help you a little. At page 94

**Comment by prncc** [comment]
Thanks for reporting. Scrapy [deliberately encodes JSON files like that](https://doc.scrapy.org/en/master/topics/feed-exports.html#feed-export-encoding). I pushed a commit that disables that behavior by adding

```
FEED_EXPORT_ENCODING = 'utf-8'
```

to `settings.py`.
