### ISSUE TITLE
Exporting reviews by keywords

### ISSUE THREAD

**Issue by ArtyCooL** [prncc/steam-scraper#7]
Hi! Thank you for fixing Encoding for unicode escape characters. You freed me from some hassle 💃 
I've got another issue with reviews exporting. Let's say I need to search some reviews by certain keywords. Maybe related to combat system or translation issue. Right now I have a file with those certain keywords that I'd like to use. So that in my output file I will only have the reviews that include those keywords in the text. 
Is there any way to create the rule in source code so it could only export reviews with these keywords?

Some keywords for example: translation, 翻訳, traducción, Übersetzung.

**Comment by prncc** [comment]
Glad to hear it. 

Regarding filtering, if your goal is to do it live (while scraping), you could instead of returning the item just check that the text contains one your keywords first:

```python
    # line 44 of review_spider.py:
    item = loader.load_item()
    for keyword in keywords:
        if keyword in item['text']:
            return item
```
